"""change uniqueness check

Revision ID: 85841af9baf8
Revises: 58fb7540d1b9
Create Date: 2026-10-06 16:01:39.549538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85841af9baf8'
down_revision: Union[str, Sequence[str], None] = '58fb7540d1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_endpoint_project_method_scenario_path'), 'endpoints', type_='unique')
    op.create_index('uq_global_endpoint_route', 'endpoints', ['method', 'scenario', 'path'], unique=True, postgresql_where=sa.text('project_id IS NULL'))
    op.create_index('uq_project_endpoint_route', 'endpoints', ['project_id', 'method', 'scenario', 'path'], unique=True, postgresql_where=sa.text('project_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_project_endpoint_route', table_name='endpoints', postgresql_where=sa.text('project_id IS NOT NULL'))
    op.drop_index('uq_global_endpoint_route', table_name='endpoints', postgresql_where=sa.text('project_id IS NULL'))
    op.create_unique_constraint(op.f('uq_endpoint_project_method_scenario_path'), 'endpoints', ['project_id', 'method', 'scenario', 'path'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
